# Generated by Django 3.2.8 on 2021-10-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211027_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredietContent',
            new_name='IngredientContent',
        ),
        migrations.RenameField(
            model_name='ingredientcontent',
            old_name='inredient',
            new_name='ingredient',
        ),
    ]
