# Generated by Django 3.2.8 on 2021-10-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcontent',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_to_recipe', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientcontent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to_ingredient', to='recipes.recipe'),
        ),
    ]
