# Generated by Django 3.2.8 on 2021-10-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211028_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='image', upload_to='recipes/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
