# Generated by Django 3.2.8 on 2021-10-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_favorited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorited',
            options={'verbose_name': 'Избранные рецепты'},
        ),
    ]
