# Generated by Django 3.2.8 on 2021-10-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorited',
            old_name='fan',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shopper',
            new_name='user',
        ),
    ]
