# Generated by Django 3.2.8 on 2021-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'г'), ('стакан', 'стакан'), ('по вкусу', 'по вкусу'), ('ст. л.', 'ст. л.'), ('шт.', 'шт.'), ('мл', 'мл'), ('ч. л.', 'ч. л.'), ('капля', 'капля'), ('звездочка', 'звездочка'), ('щепотка', 'щепотка'), ('горсть', 'горсть'), ('кусок', 'кусок'), ('кг', 'кг'), ('пакет', 'пакет'), ('пучок', 'пучок'), ('долька', 'долька'), ('банка', 'банка'), ('упаковка', 'упаковка'), ('зубчик', 'зубчик'), ('пласт', 'пласт'), ('пачка', 'пачка'), ('тушка', 'тушка'), ('стручок', 'стручок'), ('веточка', 'веточка'), ('бутылка', 'бутылка'), ('л', 'л'), ('батон', 'батон'), ('пакетик', 'пакетик'), ('лист', 'лист'), ('стебель', 'стебель')], max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#49B64E', max_length=7, verbose_name='Цвет в HEX'),
        ),
    ]
