# Generated by Django 3.2.8 on 2021-11-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20211109_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='using_ingredients',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredientcontent',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientcontent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='using_ingredients', to='recipes.recipe'),
        ),
    ]
