# Generated by Django 3.2.8 on 2021-11-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcontent',
            name='amount',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Неверное значение'}, verbose_name='Количество в рецепте'),
        ),
    ]
