# Generated by Django 3.2.8 on 2021-11-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_alter_ingredientcontent_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientcontent',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
