# Generated by Django 3.2.8 on 2021-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='юзернейм'),
        ),
    ]
